### ISSUE TITLE
構成をどのようにインストールしますか?

### ISSUE THREAD

**Issue by whyakari** [haxibami/dotfiles#1]
ブログを読みましたが、やり方がよくわかりませんでした:O 自動的にインストールするにはどうすればよいですか?

**Comment by haxibami** [comment]
このプロジェクトは chezmoi (https://www.chezmoi.io/) で管理されています。インストールは `chezmoi init --apply git@github.com:haxibami/dotfiles.git` で行えます。⚠️ 注意してください：このコマンドは、あなたの `$HOME/.config/nvim` や `.$HOME/.config/zsh` を上書きすることがあります。

参考: [chezmoi's official documentation on `chezmoi init`](https://www.chezmoi.io/reference/commands/init/)

**Comment by whyakari** [comment]
ok, thx
